feat: added build command (#26)
* added: --verbose / -v flag
* fixed paths issues on windows
* added missing e2e tests
* fixed macos python versions when testing

diff --git a/.github/workflows/e2e.yml b/.github/workflows/e2e.yml
--- a/.github/workflows/e2e.yml
+++ b/.github/workflows/e2e.yml
@@ -1,6 +1,7 @@
 name: e2e
 
 on:
+  push: {}
   schedule:
     - cron: "0 0 * * *"
 
@@ -8,22 +9,34 @@ jobs:
   e2e-test:
     runs-on: ${{ matrix.os }}
     strategy:
-      max-parallel: 4
+#      fail-fast: false
       matrix:
-        python-version: [ '3.8', '3.9', '3.10', '3.11', '3.12' ]
         os: [ ubuntu-latest, macos-latest, windows-latest ]
+        python-version: [ '3.8', '3.9', '3.10', '3.11', '3.12' ]
     steps:
       - uses: actions/checkout@v4
       - name: Set up Python ${{ matrix.python-version }}
         uses: actions/setup-python@v5
         with:
           python-version: ${{ matrix.python-version }}
+      - name: Set up Python 3.8
+        if: matrix.python-version == '3.12'
+        uses: actions/setup-python@v5
+        with:
+          python-version: "3.8"
       - name: Install global dependencies
         uses: ./.github/actions/common
-      - name: Install project dependencies (without lockfile!)
+      - name: Install pypiserver
+        if: matrix.python-version == '3.12'
         run: |
-          realm run --scope "*-e2e" -- poetry install --only dev
-          realm run --scope "*-e2e" -- poetry run pip install .
+          pipx install pypiserver[passlib] --python python3.8
+          pipx runpip pypiserver show setuptools || true
+          pipx inject pypiserver setuptools==68.2.0
+      - name: Install project dependencies
+        run: |
+          realm run --scope "*-e2e" -- poetry env use ${{ matrix.python-version }}
+          realm install --scope "*-e2e"
+          realm run --scope "*-e2e" -- poetry run pip install -U --force-reinstall .
           realm run --scope "*-e2e" -- poetry install --only-root
       - name: Run tests
         run: realm task test --scope "*-e2e"
